version: "{build}"
clone_depth: 1
image: Ubuntu

build_script:
- sh: sudo update-alternatives --set gcc /usr/bin/gcc-9
- sh: ggbuild/lua.linux make.lua release > build.ninja
- sh: ggbuild/ninja.linux -v -k 0

artifacts:
- path: release
  name: cocaine_diesel_linux
- path: base
  name: cocaine_diesel_base
